services:
  frontend:
    image: frontend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "10001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./appsettings.json:/app/appsettings.json:ro
      - aspnet_keys:/app/keys
    depends_on:
      - postgres
  
  redirect:
    image: redirect
    build:
      context: .
      dockerfile: Bmr1Redirection/Dockerfile
    ports:
      - "10000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - frontend
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: abizeitung
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpasswd
    ports:
      - "5437:5432"
    volumes:
      - sql_data:/var/lib/postgresql

volumes:
  sql_data:
  aspnet_keys:
