// <auto-generated />
using System;
using System.Collections.Generic;
using Frontend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Frontend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Frontend.Data.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("Frontend.Data.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Confirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TargetId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Frontend.Data.Entities.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SentBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Text")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("Frontend.Data.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Course")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LoginCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OldId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Permissions")
                        .HasColumnType("text[]");

                    b.Property<int>("StudentNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoginCode")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Frontend.Data.Entities.StudentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActiveUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCrossGender")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDuo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionGroupId");

                    b.ToTable("StudentCategories");
                });

            modelBuilder.Entity("Frontend.Data.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminKommentar")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AktualisiertAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Hobbys")
                        .HasColumnType("text");

                    b.Property<bool>("IstFreigegeben")
                        .HasColumnType("boolean");

                    b.Property<string>("Motto")
                        .HasColumnType("text");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Zukunftswunsch")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentProfiles");
                });

            modelBuilder.Entity("Frontend.Data.Entities.StudentVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryStudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VotedStudent2Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VotedStudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VoterStudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VotedStudent2Id");

                    b.HasIndex("VotedStudentId");

                    b.HasIndex("VoterStudentId");

                    b.HasIndex("CategoryStudentId", "VoterStudentId")
                        .IsUnique();

                    b.ToTable("StudentVotes");
                });

            modelBuilder.Entity("Frontend.Data.Entities.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("Frontend.Data.Entities.TeacherCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActiveUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionGroupId");

                    b.ToTable("TeacherCategories");
                });

            modelBuilder.Entity("Frontend.Data.Entities.TeacherQuote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Context")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsReleased")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SubmittedByStudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedByStudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherQuotes");
                });

            modelBuilder.Entity("Frontend.Data.Entities.TeacherVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryTeacherId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VotedTeacherId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VoterStudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VotedTeacherId");

                    b.HasIndex("VoterStudentId");

                    b.HasIndex("CategoryTeacherId", "VoterStudentId")
                        .IsUnique();

                    b.ToTable("TeacherVotes");
                });

            modelBuilder.Entity("Frontend.Data.Entities.Comment", b =>
                {
                    b.HasOne("Frontend.Data.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Frontend.Data.Entities.Student", "Target")
                        .WithMany("Comments")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Target");
                });

            modelBuilder.Entity("Frontend.Data.Entities.StudentProfile", b =>
                {
                    b.HasOne("Frontend.Data.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Frontend.Data.Entities.StudentVote", b =>
                {
                    b.HasOne("Frontend.Data.Entities.StudentCategory", "StudentCategory")
                        .WithMany()
                        .HasForeignKey("CategoryStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Frontend.Data.Entities.Student", "VotedStudent2")
                        .WithMany()
                        .HasForeignKey("VotedStudent2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Frontend.Data.Entities.Student", "VotedStudent")
                        .WithMany()
                        .HasForeignKey("VotedStudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Frontend.Data.Entities.Student", "VoterStudent")
                        .WithMany()
                        .HasForeignKey("VoterStudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StudentCategory");

                    b.Navigation("VotedStudent");

                    b.Navigation("VotedStudent2");

                    b.Navigation("VoterStudent");
                });

            modelBuilder.Entity("Frontend.Data.Entities.TeacherQuote", b =>
                {
                    b.HasOne("Frontend.Data.Entities.Student", "SubmittedByStudent")
                        .WithMany()
                        .HasForeignKey("SubmittedByStudentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Frontend.Data.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubmittedByStudent");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Frontend.Data.Entities.TeacherVote", b =>
                {
                    b.HasOne("Frontend.Data.Entities.TeacherCategory", "TeacherCategory")
                        .WithMany()
                        .HasForeignKey("CategoryTeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Frontend.Data.Entities.Teacher", "VotedTeacher")
                        .WithMany()
                        .HasForeignKey("VotedTeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Frontend.Data.Entities.Student", "VoterStudent")
                        .WithMany()
                        .HasForeignKey("VoterStudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TeacherCategory");

                    b.Navigation("VotedTeacher");

                    b.Navigation("VoterStudent");
                });

            modelBuilder.Entity("Frontend.Data.Entities.Student", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
